---
version: 2
triggers:
  - cron: */5 * * * *
plan:
  project-key: POLL
  name: Poll for new deliveries
  key: POLL

stages:
  - Poll stage:
      jobs: 
        - Get new deliveries

# Steps:
# - import credentials
# - list all
# - list new (how? maintain state in workspace/remote location?)
# - if no new --> abort build
# - if there is a new delivery (= a new zip file) --> trigger another pipeline w/ a filename as a parameter 
#
# Open questions:
# - how to find correct zip files?
#   * maintain state locally?
#   * matching name pattern? "*<brand>*_2021*.zip"
#   * use timestamp field?
#   * use <some other> field?
# - what if there are multiple new zips

Get new deliveries:
  tasks:
    - script: | 
        #!/bin/bash
        echo "List contents"
        echo "List new"
        

